# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `.devcontainer` directory
    directory: "src/py3-gcloud-dev/.devcontainer/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
