name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Build the Docker image
    - name: Build the Docker image
      run: |
        docker build ./src/py3-gcloud-dev/.devcontainer --file ./src/py3-gcloud-dev/.devcontainer/Dockerfile --tag jamestogethernz/py3-gcloud-dev:${{ github.sha }}
        docker tag jamestogethernz/py311-gcloud-dev:${{ github.sha }} jamestogethernz/py311-gcloud-dev:latest
    # Log in to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Push the image to Docker Hub
    - name: Push image to Docker Hub
      run: |
        docker push jamestogethernz/py3-gcloud-dev:${{ github.sha }}
        docker push jamestogethernz/py3-gcloud-dev:latest
